[General]
Name: twotoned
Author: danatationn
Version: 2.7

AllowSliderBallTint: 1
CursorExpand: 0
SpinnerFrequencyModulate: 0

[Colours]
SongSelectActiveText: 217,217,217
SongSelectInactiveText: 172,172,172

SliderBall: 217,217,217
SliderBorder: 217,217,217
SliderTrackOverride: 36,36,36

Combo1: 255,248,94
Combo2: 199,255,101
Combo3: 111,186,255
Combo4: 255,92,92

InputOverlayText: 217,217,217

[Fonts]
HitCirclePrefix: dot
HitCircleOverlap: 19

ScorePrefix: lexend
ComboPrefix: lexend

[Mania]
Keys: 4

KeyImage0: mania/key-up.png
KeyImage1: mania/key-up.png
KeyImage2: mania/key-up.png
KeyImage3: mania/key-up.png
KeyImage0D: mania/key-down.png
KeyImage1D: mania/key-down.png
KeyImage2D: mania/key-down.png
KeyImage3D: mania/key-down.png

NoteImage0: mania/note.png
NoteImage1: mania/note.png
NoteImage2: mania/note.png
NoteImage3: mania/note.png
NoteImage0H: mania/note.png
NoteImage1H: mania/note.png
NoteImage2H: mania/note.png
NoteImage3H: mania/note.png

NoteImage0L: mania/note-body.png
NoteImage1L: mania/note-body.png
NoteImage2L: mania/note-body.png
NoteImage3L: mania/note-body.png
NoteImage0T: mania/note-tail.png
NoteImage1T: mania/note-tail.png
NoteImage2T: mania/note-tail.png
NoteImage3T: mania/note-tail.png

StageHint:

ColumnWidth: 48,48,48,48
ColumnStart: 300
HitPosition: 432
ColumnLineWidth: 0,0,0,0
JudgementLine: 0
;KeysUnderNotes: 1
